name: Deploy to Staging

on:
  push:
    branches: ["staging_server"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/html/staging.transportanycar.com || exit 1
            git reset --hard
            git clean -fd
            git pull origin staging_server
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
