name: Deploy to Staging

on:
  push:
    branches: ["staging"]

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest
    # Add this only if using Environment Secrets:
    # environment:
    #   name: Staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.STAGING_HOST }}
          username: ${{ secrets.STAGING_USER }}
          port: ${{ secrets.STAGING_PORT }}
          key: ${{ secrets.STAGING_SSH_KEY }}
          script: |
            cd /var/www/html/staging.transportanycar.com
            git pull origin staging
            
